<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/11/06 14:32:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=learning1.4',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
